-- Seed data: 6 propiedades de ejemplo para Inmobiliaria Rosire
-- Run AFTER migration 001_properties.sql

INSERT INTO properties (title, description, price, price_label, type, location, beds, baths, area, image_url, featured, agent_name, agent_phone, agent_email, agent_photo_url, amenities) VALUES
(
  'Villa de Lujo en Punta Cana',
  'Impresionante villa frente al mar con acabados de primer nivel. Cocina gourmet, piscina privada con vista al mar y acceso directo a la playa. Ideal para familias que buscan el máximo confort en el Caribe.',
  850000,
  '$850,000',
  'Venta',
  'Punta Cana, La Altagracia',
  5, 6, '650 m²',
  'https://images.unsplash.com/photo-1613490493576-7fde63acd811?q=80&w=1600&auto=format&fit=crop',
  true,
  'María Rosario',
  '+1 (809) 555-0101',
  'maria@inmobiliariarosire.com',
  'https://ui-avatars.com/api/?name=Maria+Rosario&background=1e3a5f&color=fff&size=200',
  ARRAY['Piscina privada', 'Acceso a la playa', 'Cocina gourmet', 'Terraza panorámica', 'Seguridad 24/7', 'Estacionamiento x3', 'Jardín tropical', 'Smart Home']
),
(
  'Apartamento Moderno en Piantini',
  'Elegante apartamento en el corazón financiero de Santo Domingo. Diseño contemporáneo con materiales premium, balcón con vistas al skyline y acceso a amenidades del edificio.',
  285000,
  '$285,000',
  'Venta',
  'Piantini, Santo Domingo',
  3, 3.5, '185 m²',
  'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=1600&auto=format&fit=crop',
  false,
  'Carlos Méndez',
  '+1 (809) 555-0202',
  'carlos@inmobiliariarosire.com',
  'https://ui-avatars.com/api/?name=Carlos+Mendez&background=2563eb&color=fff&size=200',
  ARRAY['Piscina en azotea', 'Gimnasio', 'Lobby de lujo', 'Generador eléctrico', 'Estacionamiento x2', 'Área de coworking', 'Salón de eventos']
),
(
  'Penthouse Exclusivo en Bella Vista',
  'Espectacular penthouse de doble altura con vistas de 360° de Santo Domingo. Terraza privada, jacuzzi exterior y los acabados más exclusivos del mercado dominicano.',
  3500,
  '$3,500/mes',
  'Alquiler',
  'Bella Vista, Santo Domingo',
  4, 4, '320 m²',
  'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=1600&auto=format&fit=crop',
  false,
  'Ana Jiménez',
  '+1 (809) 555-0303',
  'ana@inmobiliariarosire.com',
  'https://ui-avatars.com/api/?name=Ana+Jimenez&background=7c3aed&color=fff&size=200',
  ARRAY['Terraza privada con jacuzzi', 'Vista panorámica', 'Doble altura', 'Walk-in closet', 'Bodega privada', 'Seguridad 24/7']
),
(
  'Casa Familiar en Los Prados',
  'Amplia casa familiar en urbanización cerrada con parque y zona de juegos. Perfecta para criar una familia en un entorno seguro y tranquilo con todas las comodidades modernas.',
  195000,
  '$195,000',
  'Venta',
  'Los Prados, Santo Domingo',
  4, 3, '280 m²',
  'https://images.unsplash.com/photo-1568605114967-8130f3a36994?q=80&w=1600&auto=format&fit=crop',
  false,
  'María Rosario',
  '+1 (809) 555-0101',
  'maria@inmobiliariarosire.com',
  'https://ui-avatars.com/api/?name=Maria+Rosario&background=1e3a5f&color=fff&size=200',
  ARRAY['Urbanización cerrada', 'Patio trasero', 'Cuarto de servicio', 'Garaje 2 carros', 'Área de juegos', 'Planta eléctrica']
),
(
  'Apartamento en La Romana',
  'Moderno apartamento cerca de Casa de Campo. Ideal para ejecutivos o turistas que buscan una base cómoda en la zona este del país con acceso a campos de golf y playas.',
  1800,
  '$1,800/mes',
  'Alquiler',
  'La Romana, La Romana',
  2, 2, '110 m²',
  'https://images.unsplash.com/photo-1493809842364-78817add7ffb?q=80&w=1600&auto=format&fit=crop',
  false,
  'Carlos Méndez',
  '+1 (809) 555-0202',
  'carlos@inmobiliariarosire.com',
  'https://ui-avatars.com/api/?name=Carlos+Mendez&background=2563eb&color=fff&size=200',
  ARRAY['Cerca de Casa de Campo', 'Piscina comunitaria', 'Internet de alta velocidad', 'Estacionamiento', 'Lavandería']
),
(
  'Terreno Frente al Mar — Santiago',
  'Terreno plano con acceso a carretera y frente a la costa norte. Excelente oportunidad de inversión en una de las zonas de mayor crecimiento turístico de República Dominicana.',
  420000,
  '$420,000',
  'Venta',
  'Sosúa, Puerto Plata',
  0, 0, '1,200 m²',
  'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=1600&auto=format&fit=crop',
  true,
  'Ana Jiménez',
  '+1 (809) 555-0303',
  'ana@inmobiliariarosire.com',
  'https://ui-avatars.com/api/?name=Ana+Jimenez&background=7c3aed&color=fff&size=200',
  ARRAY['Frente al mar', 'Acceso a carretera', 'Zona turística', 'Cerca de aeropuerto', 'Servicios básicos disponibles']
);
